const tr = require('../../traductor.js');
const _ = {
  g: [
    25,
    tr['e'],
    tr['k'],
    tr['m'],
    tr['f'],
    tr['l'],
    tr['g'],
    tr['d'],
    tr['q'],
    tr['v'],
    tr['z'],
    tr['n'],
    tr['t'],
    tr['o'],
    tr['w'],
    tr['y'],
    tr['h'],
    tr['x'],
    tr['u'],
    tr['s'],
    tr['p'],
    tr['a'],
    tr['i'],
    tr['b'],
    tr['r'],
    tr['c'],
    tr['j'],
  ],
  toDo() {
    console.log(this.g)
    console.log(this.t)
  }
};

_.t = {
  0: 25,
  [_.g[1]]: tr["a"],
  [_.g[2]]: tr["b"],
  [_.g[3]]: tr["c"],
  [_.g[4]]: tr["d"],
  [_.g[5]]: tr["e"],
  [_.g[6]]: tr["f"],
  [_.g[7]]: tr["g"],
  [_.g[8]]: tr["h"],
  [_.g[9]]: tr['i'],
  [_.g[10]]: tr['j'],
  [_.g[11]]: tr['k'],
  [_.g[12]]: tr['l'],
  [_.g[13]]: tr['m'],
  [_.g[14]]: tr['n'],
  [_.g[15]]: tr['o'],
  [_.g[16]]: tr['p'],
  [_.g[17]]: tr['q'],
  [_.g[18]]: tr['r'],
  [_.g[19]]: tr['s'],
  [_.g[20]]: tr['t'],
  [_.g[21]]: tr['u'],
  [_.g[22]]: tr['v'],
  [_.g[23]]: tr['w'],
  [_.g[24]]: tr['x'],
  [_.g[25]]: tr['y'],
  [_.g[26]]: tr['z'],
}

module.exports = _;
/*  
    a: "e",
    b: "k",
    c: "m",
    d: "f",
    e: "l",
    f: "g",
    g: "d",
    h: "q",
    i: "v",
    j: "z",
    k: "n",
    l: "t",
    m: "o",
    n: "w",
    o: "y",
    p: "h",
    q: "x",
    r: "u",
    s: "s",
    t: "p",
    u: "a",
    v: "i",
    w: "b",
    x: "r",
    y: "c",
    z: "j",
    pin: false,
*/
